# Site settings
title: Brycon Carpenter Personal Portfolio
email: bcarpenter1994@hotmail.com
baseurl: ""
linked_in_name: bryconc 
github_username: bryconc

# Build settings
markdown: kramdown

# Outputting

permalink: /blogs/:year-:month-:day/:title/